// app/team/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';

import { AuthService } from '../shared/auth.service';
import { AppStateService } from '../shared/app-state.service';

@Component({
	// moduleId: module.id,
	selector: 'my-admin-login',
	templateUrl: 'login.component.html'
})
export class LoginComponent implements OnInit {
	chienDichList = [];
	loginData = {
		chien_dich_id: 0,
		name: '',
		password: ''
	};
	password = '';
	isLoginError = false;

	constructor(
		private appState: AppStateService,
		private auth: AuthService,
		private router: Router,
		private http: HttpClient) {}

	ngOnInit() {
		// Get list chien dich
		this.http.get<any>(this.appState.state.apiRoot + 'team/chiendichdangmo')
		.subscribe(data => {
			this.chienDichList = data;
			if (this.chienDichList.length) {
				this.loginData.chien_dich_id = this.chienDichList[0].id;
			}
		});
	}

	login() {
		this.isLoginError = false;
		console.log(this.loginData);
		this.auth.login(this.loginData)
		.subscribe(data => {
			if (data.result) {
				this.auth.authData.isLogin = true;
				this.router.navigateByUrl('/bando');
			} else {
				this.isLoginError = true;
			}
		})
	}
}
<form class="mt-3">
	<div class="form-group">
		<label>Chọn chiến dịch</label>
		<select class="form-control" [(ngModel)]="loginData.chien_dich_id" name="chien_dich_id">
			<option *ngFor="let item of chienDichList" [value]="item.id">{{item.name}}</option>
		</select>
	</div>
	<div class="form-group">
		<label>Tên đội</label>
		<input type="text" class="form-control" [(ngModel)]="loginData.name" name="name" placeholder="Tên đội"/>
	</div>
	<div class="form-group">
		<label>Mật khẩu</label>
		<input type="password" class="form-control" [(ngModel)]="loginData.password" name="password" placeholder="Mật khẩu"/>
	</div>
	<ngb-alert [dismissible]="false" *ngIf="isLoginError">
	    Đăng nhập không thành công.
  	</ngb-alert>
	<button type="submit" class="btn btn-primary" (click)="login()">Đăng nhập</button>
</form>

// react/doichoi/src/pages/login/login.tsx
import React, { ChangeEvent, FormEvent, useEffect } from 'react';
import {
  Form,
  Col
} from 'react-bootstrap';
import {
  Redirect,
} from 'react-router-dom';

import loginService from './login.service';
import chienDichService from '../chien-dich/chien-dich.service';

const Login: React.FC = () => {
  const [listChienDich, setListChienDich] = React.useState<any[]>([]);
  const [loginData, setLoginData] = React.useState<any>({});
  const [isLoggedIn, setIsLoggedIn] = React.useState<boolean>(false);
  const [isLoggedInError, setIsLoggedInError] = React.useState<boolean>(false);

  useEffect(() => {
    chienDichService.listOpen().then((res: any) => {
      setListChienDich(res.data);
      if (res.data.length) {
        setLoginData({chien_dich_id: res.data[0].id});
      }
    });
  }, []);

  function submit(event: FormEvent) {
    event.preventDefault();
    setIsLoggedInError(false);
    loginService.login(loginData).then(
      (res: any) => {
        if (res.data.result) {
          
          setIsLoggedIn(true);
        } else {
          setIsLoggedInError(true);
        }
      },
      () => {
        setIsLoggedInError(true);
      }
    )
  }

  function handleInputChange(event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) {
    const name = event.target.name;
    setLoginData({...loginData, [name]: event.target.value});
  }

  if(isLoggedIn) {
    return <Redirect to="/chiendich" />
  };

  return (
    <div>
      <h2>Đăng nhập vào chiến dịch</h2>
      <Form onSubmit={(e) => submit(e)}>

          <Form.Group>
            <Form.Label>Chọn chiến dịch</Form.Label>
            <Form.Control
              as="select"
              name="chien_dich_id"
              onChange={handleInputChange}
            >
              {listChienDich.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}
            </Form.Control>
          </Form.Group>

          <Form.Group>
            <Form.Label>Tên đội</Form.Label>
            <Form.Control
              type="text"
              placeholder="Nhập tên đội"
              name="name"
              onChange={handleInputChange}
              />
          </Form.Group>

          <Form.Group>
            <Form.Label>Mật khẩu</Form.Label>
            <Form.Control
              type="password"
              placeholder="Nhập mật khẩu"
              name="password"
              onChange={handleInputChange}
              />
          </Form.Group>


        {isLoggedInError &&
          <div className="alert alert-danger" role="alert">
            Đăng nhập lỗi. Chắc là mật khẩu sai rồi.
          </div>
        }

        <button className="btn btn-primary">Đăng nhập</button>
      </Form>
    </div>
  );
}

export default Login;
